cmake_minimum_required(VERSION 4.0)
project(PointerTasks2)

set(CMAKE_CXX_STANDARD 20)

add_executable(PointerTasks2 main.cpp
        SwapPointers.cpp
        DynamicCreateArray.cpp
        SummAllElem.cpp
        CharArrayAndSort.cpp
        DynamicManageMeshStruct.cpp
        DynamicStructNeuralLayer.cpp
        DistributionLoadInSystem.cpp)
