cmake_minimum_required(VERSION 4.0)
project(SmartPointers)

set(CMAKE_CXX_STANDARD 20)

add_executable(SmartPointers main.cpp
        Task1.cpp
        Task2.cpp
        Task3.cpp
        Task4.cpp
        Task5.cpp
        Task6.cpp
        Task7.cpp
        Task8.cpp
        Task9.cpp
        Task10.cpp
        Task11.cpp
        Task12.cpp
)
